### ISSUE TITLE
不好用,clap也装了，你的demo代码放到全是错

### ISSUE THREAD

**Issue by 107295472** [reiase/hyperparameter#12]

**Comment by reiase** [comment]
自己测试了以下，0.5.7版本，依赖处理有些问题。这个示例：https://github.com/reiase/hyperparameter/blob/master/examples/clap_app.rs
需要给自己的项目添加两个依赖：
```toml
const-str = "0.5.6"
xxhash-rust = { version = "0.8.7", features = ["const_xxh64"] }
```
